In [2]:
# Practicing with Numpy 

First will explore how to create **1D and 2D arrays** using NumPy, and perform various operations such as indexing, slicing, reshaping, and arithmetic.

In [4]:
import numpy as np

## Creating 1D and 2D Arrays

In [6]:
# 1D array
arr1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr1d)

1D Array: [1 2 3 4 5]


In [7]:
# Note the 1D array above. It is also called a vector

In [22]:
# How do we access elements of the 1d array?
# array indices go from 0 to n-1, where n is the number of elements

In [23]:
# to access the zeroth element
print (arr1d[0])

# to access the 2nd element
print(arr1d[2])

# to access the last element of this array
print(arr1d[4])

# to access the last element of the array, we can also use the trick
print(arr1d[-1])


1
3
5
5


In [8]:
# 2D array
# For a 2D array, we have rows and columns
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2d)

2D Array:
 [[1 2 3]
 [4 5 6]]


In [13]:
# In the 2D array above, we have 2 rows and 3 columns
# here is how we access specific array elements

In [24]:
print(arr2d[0,0])  # row 0, col 0
print(arr2d[1,1])  # row 1, col 1
print(arr2d[1,2])  # row 1, col 2

1
5
6


## Array Properties

In [25]:
print("Shape of arr1d:", arr1d.shape)
print("Shape of arr2d:", arr2d.shape)

print("Dimensions of arr1d:", arr1d.ndim)
print("Dimensions of arr2d:", arr2d.ndim)

print("Data type of arr1d:", arr1d.dtype)

Shape of arr1d: (5,)
Shape of arr2d: (2, 3)
Dimensions of arr1d: 1
Dimensions of arr2d: 2
Data type of arr1d: int64


## Indexing and Slicing

In [26]:
# Indexing 1D array
print("First element of arr1d:", arr1d[0])
print("Last element of arr1d:", arr1d[-1])

# Slicing 1D array
print("Elements from index 1 to 3:", arr1d[1:4])

# Indexing 2D array
print("Element at row 0, col 1:", arr2d[0, 1])

# Slicing 2D array
print("First row:", arr2d[0, :])
print("Second column:", arr2d[:, 1])

First element of arr1d: 1
Last element of arr1d: 5
Elements from index 1 to 3: [2 3 4]
Element at row 0, col 1: 2
First row: [1 2 3]
Second column: [2 5]


## Array Operations

In [27]:
# Arithmetic operations
print("arr1d + 10:", arr1d + 10)
print("arr1d * 2:", arr1d * 2)

# Element-wise operations on 2D array
print("arr2d squared:\n", arr2d ** 2)

# Broadcasting
print("arr2d + arr1d[:3]:\n", arr2d + arr1d[:3])

arr1d + 10: [11 12 13 14 15]
arr1d * 2: [ 2  4  6  8 10]
arr2d squared:
 [[ 1  4  9]
 [16 25 36]]
arr2d + arr1d[:3]:
 [[2 4 6]
 [5 7 9]]


## Useful NumPy Functions

Observe what each of the following lines does

In [47]:
print(np.zeros(5))
print("The above line creates a 1d array with 5 elements, all of which are zero")
print (" " )

print(np.ones((2, 3)))
print("The above line creates a 2d array with 2 rows and 5 columns, all of which are 1")
print (" " )


print(np.arange(0, 10, 2))
print("The above line creates a 1d array with even integers")
print (" " )


print(np.arange(20, 10, -2))
print("The above line creates a 1d array with even integers but ordered in reverse from 20 to 12")
print (" " )


print(np.linspace(0, 1, 5))
print("The above line creates a 1d array with 4 linearly spaced elements from 0 to 1")
print("The spacing between elements is (1-0)/(5-1) = 0.25")

print (" " )


[0. 0. 0. 0. 0.]
The above line creates a 1d array with 5 elements, all of which are zero
 
[[1. 1. 1.]
 [1. 1. 1.]]
The above line creates a 2d array with 2 rows and 5 columns, all of which are 1
 
[0 2 4 6 8]
The above line creates a 1d array with even integers
 
[20 18 16 14 12]
The above line creates a 1d array with even integers but ordered in reverse from 20 to 12
 
[0.   0.25 0.5  0.75 1.  ]
The above line creates a 1d array with 4 linearly spaced elements from 0 to 1
The spacing between elements is (1-0)/(5-1) = 0.25
 


In [43]:
# Another example of creating arrays
A = np.array([np.arange(5), np.arange(5)])
print(A)
print("in this example we created an array with 2 rows and 5 columns")

print(" ")
print("observe what the following line does") 
B = np.array([np.arange(0,10,2), np.arange(10,0,-2)])
print(B)

[[0 1 2 3 4]
 [0 1 2 3 4]]
in this example we created an array with 2 rows and 5 columns
 
observe what the following line does
[[ 0  2  4  6  8]
 [10  8  6  4  2]]


### Exercise 1

- Create a 1d array of odd numbers from 1 to 21

- Then create an array that reverses the order (i.e. from 21 to 1)


In [2]:
# Your solution here

### Exercise 2

- Create a 1d array of 10 numbers, each of which is spaced 0.5


In [3]:
# Your solution here

# Exercise 3

- Create a 2d array with 3 rows and 3 columns, with each element being 0
- Create a 2d array with 5 rows and 2 columns with the first 
column being even numbers and the second column odd numbers

In [ ]:
# Your solution here

### Exercise 4

Create two 1D arrays `a = [1,2,3,4,5]` and `b = [5,4,3,2,1]`. Compute:
1. `a + b`
2. `a - b`
3. `a * b` (element-wise)
4. `a / (b+1)`

In [ ]:
# Your solution here

### Exercise 5: 2D Arrays

Create two 2D arrays:
```
A = [[1,2],[3,4]]
B = [[2,0],[1,3]]
```
Compute:
1. `A + B`
2. `A - B`
3. `A * B` (element-wise)
4. Matrix product `A @ B`


In [2]:
# Your solution here

### Exercise 6: Newton's Second Law

Given masses `m = [1,2,3]` kg and accelerations `a = [3,2,1]` m/s^2, compute the forces using $F = ma$.

In [ ]:
# Your solution here

### Exercise 7: Kinetic Energy

Suppose we have masses `m = [1, 2, 3]` (kg) and velocities `v = [2, 4, 6]` (m/s).

Compute the **kinetic energy** for each mass: $KE = \tfrac{1}{2} m v^2$.

In [ ]:
# Your solution here

### Exercise 8: Exponential Series

Approximate $e^x$ for $x=1$ using the series expansion:

$$e^x = 1 + x + \frac{x^2}{2!} + \frac{x^3}{3!} + \cdots$$

Compute the approximation using the first **5 terms**.

In [5]:
# Your solution here